
server:
  port: 8081

jwt:
  private:
    key: classpath:app.key
  public:
    key: classpath:app.pub

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5433}/${DB_NAME:bdd_auth}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    
  rabbitmq:
    # communication inter-service (email)
    exchange: email.exchange
    routingkey: email.routingkey
    queue: email.queue


logging:
  level:
    org.hibernate.envers.boot: OFF
